spring:

    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp

    datasource:
        url: jdbc:mysql://localhost/Sharingbox
        username: sharingboxusr
        password: sharingboxpass

    jpa:
      properties:
        hibernate:
          current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext 
    
server:
  port: 8080
            